---
downloads: ~/.ansible-downloads/

dotfiles_repo: https://github.com/jcannava/dotfiles
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .bash_profile
  - .bashrc
  - .tmux.conf
  - .vimrc

dockitems_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar
  - Photo Booth
  - Mission Control
  - Siri

dockitems_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: iTerm2
    path: "/Applications/iTerm.app"
    pos: 2
  - name: Messages
    path: "/Applications/Messages.app"
    pos: 3
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 4
  - name: Zoom.us
    path: "/Applications/zoom.us.app"
    pos: 5
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 6

homebrew_installed_packages:
  - autoconf
  - automake
  - bash-completion
  - chromedriver
  - cowsay
  - dockutil
  - gettext
  - git
  - go
  - kubernetes-cli
  - nmap
  - openssl
  - ssh-copy-id
  - tmux
  - { name: vim, install_options: "override-system-vi"}
  - wget

homebrew_upgrade_all_packages: no

homebrew_taps:
  - homebrew/core
  - caskroom/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - google-chrome
  - iterm2
  - slack
  - sublime-text
  - spotify
  - vagrant
  - virtualbox
  - zoomus
