---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  roles:
   - role: geerlingguy.homebrew
     tags: ['homebrew']
   - role: geerlingguy.mas
     when: mas_installed_apps

  tasks:
    - name: Clone dotfiles
      git:
        repo: git://github.com/jcannava/dotfiles
        dest: ~/.dotfiles

    - name: Get git-prompt.sh
      get_url:
        url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
        dest: ~/.dotfiles/git-prompt.sh

    - name: Run deploy.sh (dotfiles)
      shell: ~/.dotfiles/deploy.sh

    - name: Make vim colorscheme directory
      file: 
        path: ~/.vim/pack/themes/opt
        state: directory
        mode: 0755

    - name: Make vim autoload directory
      file:
        path: ~/.vim/autoload
        state: directory
        mode: 0755

    - name: Make vim bundle directory
      file: 
        path: ~/.vim/bundle
        state: directory
        mode: 0755

    - name: Install powerline
      shell: pip install --user git+git://github.com/powerline/powerline#egg=powerline-status

    - name: install vim colorscheme
      git:
        repo: https://github.com/lifepillar/vim-solarized8.git
        dest: ~/.vim/pack/themes/opt/solarized8

    - name: Remove items from Dock
      shell: dockutil --remove '{{ item }}'
      ignore_errors: true
      with_items: '{{ dockitems_to_remove }}'

    - name: Check if items in dock exist
      shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}' --no-restart
      with_items: '{{ dockitems_to_persist }}'
      ignore_errors: true

    - name: Fix Order
      shell: dockutil --move '{{ item.name }}' --position {{ item.pos }} --no-restart
      with_items: '{{ dockitems_to_persist }}'
      ignore_errors: true

    - name: Add Folders
      shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}' --view grid --display folder --before Trash --no-restart
      with_items: '{{ dockfolders_to_persist }}'
      ignore_errors: true

    - name: Reduce Dock Size to 30
      shell: defaults write com.apple.dock tilesize -int 30

    - name: Show ~/Library
      shell: chflags nohidden ~/Library

    - name: Show External Drives on the Desktop
      shell: defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true

    - name: Show Removable Media on the Desktop
      shell: defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

    - name: Show the Status Bar in Finder
      shell: defaults write com.apple.finder ShowStatusBar -bool true

    - name: Show the Path Bar in Finder
      shell: defaults write com.apple.finder ShowPathbar -bool true

    - name: Restart Finder
      shell: killall Finder

    - name: Enable TimeMachine
      shell: tmutil enable
      become: true

    - name: Set path for iterm preferences
      shell: defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/dotfiles/"

    - name: Restore iterm preferences
      shell: defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

    - name: Set Mouse Scroll Direction to classic
      shell: defaults write com.apple.swipescrolldirection -bool false
